# GENERATED by tests/generate_vulture_whitelist.py — DO NOT EDIT BY HAND.
# Regenerate: ./build.sh vulture-whitelist
#
# vulture (min_confidence=60) reports @dataclass fields as "unused variable":
# they cross a JSON / CLI / plugin boundary static analysis cannot see. Each
# bare name below marks one field "used". SSOT = the @dataclass definitions in
# agent_runner/; a new field is covered by regenerating, never by editing here.

# agent_runner.agent_runtime.RunResult
exit_code
duration_s
timed_out
pid
killed_for_grace
grace_kill_children

# agent_runner.api_types.Alert
severity
detector
message
context
ts
auto_action

# agent_runner.api_types.DirtyOutcome
kind
ref

# agent_runner.api_types.InitResult
work_dir
files_created
committed
preset

# agent_runner.api_types.InstallResult
unit_path
monitor_unit_path
enabled
started

# agent_runner.api_types.ProjectState
project
status
defenses
current_round
recent_rounds
orphan
system
service
recent_events
recent_hook_failures
recent_blips

# agent_runner.api_types.RateLimitState
throttled_until_epoch
limit_type
agent
since_round

# agent_runner.api_types.RoundResult
round_num
phase
started_at
ended_at
exit_code
duration_s
timed_out
log_path
dirty_files
stashed
dirty_outcome
killed_for_grace

# agent_runner.api_types.RoundView
round_num
phase
started_at
duration_so_far_s
pid
exit_code
timed_out
log_path
log_tail
recent_events

# agent_runner.api_types.ServiceStatus
mode
active
pid
uptime_s
unit_file
rate_limit

# agent_runner.api_types.SystemMetrics
mem_total_mb
mem_available_mb
disk_used_pct
disk_free_gb
load_1m
cpu_pct
agent_process_count

# agent_runner.api_types.TransientErrorState
reset_at_epoch
classification
agent
since_round

# agent_runner.config.AgentConfig
command
prompt_arg_template
name
env
prompt_delivery

# agent_runner.config.Config
agent
runtime
prompt
vcs
monitor
phases
plugins

# agent_runner.config.MonitorConfig
auth_fail_patterns
auth_fail_hint
auto_stop_on
remote_failure_tolerance_s
anomaly_repetitive_window
anomaly_repetitive_threshold
host_health
round_progress_interval_s
supervisor_stale_threshold_s

# agent_runner.config.MonitorHostHealthConfig
mem_avail_min_mb
disk_warning_pct
disk_critical_pct

# agent_runner.config.PhaseOverride
round_timeout_s
disable_pre_round_hooks
prompt_files

# agent_runner.config.PhasesConfig
list
overrides

# agent_runner.config.PluginsConfig
disable
raw

# agent_runner.config.PromptConfig
file
files
inject_context
context_injection_mode
concat_separator
strip_yaml_frontmatter

# agent_runner.config.RuntimeConfig
work_dir
log_dir
round_timeout_s
restart_delay_s
disable_pre_round_hooks
round_log_retention
narrative_file
transient_error_action
max_rounds
stop_file
substrate_fingerprint_paths
fresh_eyes_every_n
dry_run
max_grace_after_result_s
grace_kill_ignore_patterns

# agent_runner.config.VcsConfig
stash_idempotency_s
dirty_action

# agent_runner.context_store.OrphanState
round_num
files
stashed_ref
stash_message
timestamp
phase

# agent_runner.context_store.Status
round_num
running
last_completed_at
last_exit_code
last_duration_s
current_phase
phase_index

# agent_runner.defenses.Defense
name
value
codifies
guarded_by
current_state

# agent_runner.hooks.HookContext
work_dir
log_dir
project
round_num
phase
agent_name
agent_binary
agent_log_path
dry_run
anomaly_repetitive_window
anomaly_repetitive_threshold
vcs

# agent_runner.hooks.VcsHookView
dirty_action
stash_idempotency_s

# agent_runner.lifecycle.PIDFile
path

# agent_runner.monitor.LocalSource
log_dir

# agent_runner.monitor.RemoteSource
host
project

# agent_runner.startup_check.CheckResult
name
ok
reason
how_to_fix

# agent_runner.vcs_state.StashRef
sha
message
reused
