"""Project scaffold for `agent-runner init`.

Writes three files into a git repo:
  agent-runner.toml      — copy of example template, project name substituted
  prompts/main.md        — neutral 8-line placeholder
  .gitignore             — append "logs/" if missing

Optionally commits in one step (default true via the CLI).
"""

from __future__ import annotations

import subprocess  # noqa: TID251 — scaffold needs git for the commit step
from pathlib import Path

from agent_runner.api_types import InitResult
from agent_runner.vcs_state import is_git_repo

_TOML_TEMPLATE = """\
# agent-runner.toml — generated by `agent-runner init`. Edit fields as needed.

# 'claude' below is the reference agent. Replace with any prompt-arg CLI:
# command = ["gemini", "chat"], prompt_arg_template = ["--prompt", "{prompt}"]
[agent]
command = ["claude", "--model", "claude-opus-4-7",
           "--dangerously-skip-permissions",
           "--verbose", "--output-format", "stream-json"]
prompt_arg_template = ["-p", "{prompt}"]
# name = "claude"            # optional — provider identifier; defaults to command[0]

[runtime]
work_dir = "."
log_dir = "~/.agent-runner/{project}/logs"
round_timeout_s = 1800
restart_delay_s = 3

[prompt]
file = "./prompts/main.md"
inject_context = true

# [phases]                # optional — uncomment for phase rotation
# list = ["diverge", "converge", "refine"]

[vcs]
orphan_action = "stash"
stash_idempotency_s = 5

# [monitor]               # optional — auto-stop policy overrides
# auto_stop_on = ["oauth_fail", "disk_critical"]
# disk_warning_pct = 90.0
# disk_critical_pct = 95.0

# [llm]                   # Phase 3 — reserved, not yet used
# endpoint = "anthropic"
# api_key_env = "ANTHROPIC_API_KEY"
# model = "claude-haiku-4-5"
"""

_PROMPT_TEMPLATE = """\
# Agent Prompt

You are an autonomous agent working on this project. Each round begins with a
`round-context` JSON block prepended above this prompt — read it first.

If `round_num == 1`: orient yourself with the project structure (README, file tree).
If `previous.exit_code != 0`: investigate what went wrong before resuming.
If `orphan_stash` is present: decide salvage (`git stash pop`) or abandon (`git stash drop`).

Always: commit and push your work before exiting the round. The supervisor will
auto-stash if you forget, but explicit commits with meaningful messages are better.
"""

_GITIGNORE_LINE = "logs/"


def scaffold_project(work_dir: Path, *, force: bool, commit: bool) -> InitResult:
    if not is_git_repo(work_dir):
        raise RuntimeError(f"{work_dir} is not a git working tree — run `git init` first")

    toml_path = work_dir / "agent-runner.toml"
    prompt_dir = work_dir / "prompts"
    prompt_path = prompt_dir / "main.md"
    gitignore_path = work_dir / ".gitignore"

    if toml_path.exists() and not force:
        raise FileExistsError(f"{toml_path} already exists; pass force=True to overwrite")

    files_created: list[Path] = []

    project = work_dir.resolve().name or "default"
    toml_path.write_text(_TOML_TEMPLATE.replace("{project}", project))
    files_created.append(toml_path)

    prompt_dir.mkdir(parents=True, exist_ok=True)
    if not prompt_path.exists() or force:
        prompt_path.write_text(_PROMPT_TEMPLATE)
        files_created.append(prompt_path)

    existing = gitignore_path.read_text() if gitignore_path.exists() else ""
    if _GITIGNORE_LINE not in existing.splitlines():
        new_text = existing
        if existing and not existing.endswith("\n"):
            new_text += "\n"
        new_text += _GITIGNORE_LINE + "\n"
        gitignore_path.write_text(new_text)
        files_created.append(gitignore_path)

    committed = False
    if commit:
        subprocess.run(["git", "add", "."], cwd=work_dir, check=True)
        r = subprocess.run(
            [
                "git",
                "-c",
                "commit.gpgsign=false",
                "commit",
                "-q",
                "-m",
                "chore: agent-runner initial config",
            ],
            cwd=work_dir,
            capture_output=True,
            text=True,
        )
        committed = r.returncode == 0  # may fail if nothing changed

    return InitResult(work_dir=work_dir, files_created=files_created, committed=committed)
