"""Generate ``.vulture-whitelist.py`` from every ``@dataclass`` in agent_runner/.

DEV TOOLING — lives in ``tests/`` so it stays out of the shipped wheel
(pyproject ``packages = ["agent_runner"]``). Two callers:

* ``./build.sh vulture-whitelist`` — rewrites the committed whitelist.
* ``tests/invariants/test_vulture_whitelist_generated.py`` — the diff-clean guard.

WHY it exists: vulture (min_confidence=60) reports ``@dataclass`` fields as
"unused variable" — they are read across a JSON / CLI / plugin boundary that
static analysis cannot see. Rather than hand-list those fields (which would
duplicate the public API surface and silently drift), we regenerate a reference
to every field straight from the dataclass definitions — the SSOT. Adding a
field is covered by regenerating; it can never drift out of the whitelist.
"""

from __future__ import annotations

import dataclasses
import importlib
import pkgutil
from pathlib import Path

import agent_runner

WHITELIST_PATH = Path(__file__).resolve().parent.parent / ".vulture-whitelist.py"

_HEADER_LINES = [
    "# GENERATED by tests/generate_vulture_whitelist.py — DO NOT EDIT BY HAND.",
    "# Regenerate: ./build.sh vulture-whitelist",
    "#",
    '# vulture (min_confidence=60) reports @dataclass fields as "unused variable":',
    "# they cross a JSON / CLI / plugin boundary static analysis cannot see. Each",
    '# bare name below marks one field "used". SSOT = the @dataclass definitions in',
    "# agent_runner/; a new field is covered by regenerating, never by editing here.",
]


def _iter_dataclasses() -> list[tuple[str, type]]:
    """Return ``(qualified_name, class)`` for every ``@dataclass`` defined in the package.

    Discovery is by runtime import (the ``_docgen`` pattern), so inherited and
    decorator-produced fields resolve exactly as at runtime. Sorted by qualified
    name for deterministic output; the diff-clean invariant depends on it.
    """
    module_names = [agent_runner.__name__]
    for info in pkgutil.walk_packages(agent_runner.__path__, agent_runner.__name__ + "."):
        # `__main__` submodules execute the CLI at import time — never import them.
        if info.name.rsplit(".", 1)[-1] == "__main__":
            continue
        module_names.append(info.name)

    found: dict[str, type] = {}
    for module_name in module_names:
        module = importlib.import_module(module_name)
        for obj in vars(module).values():
            if (
                isinstance(obj, type)
                and dataclasses.is_dataclass(obj)
                and obj.__module__ == module_name  # defined here, not re-exported
            ):
                found[f"{obj.__module__}.{obj.__qualname__}"] = obj
    return sorted(found.items())


def generate() -> str:
    """Render the whitelist text (classes sorted; fields in definition order)."""
    lines = list(_HEADER_LINES)
    for qualname, cls in _iter_dataclasses():
        lines.append("")
        lines.append(f"# {qualname}")
        lines.extend(f.name for f in dataclasses.fields(cls))
    return "\n".join(lines) + "\n"


def main() -> int:
    WHITELIST_PATH.write_text(generate(), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
